### ISSUE TITLE
Unwanted <br/> generated when markdown contains reference links

### ISSUE THREAD

**Issue by gribnoysup** [developit/snarkdown#14]
Right now snarkdown generates excessive `<br/>` tag at the end of html. 

With markdown like this:

```markdown
hello [World]

[world]: http://world.com
```

You'll get this html:

```html
hello <a href="http://world.com">World</a><br />
```

The easiest fix will be to move replace for trailing newlines to the end of this code:

```js
md = md.replace(/^\n+|\n+$/g, '').replace(/^\[(.+?)\]:\s*(.+)$/gm, (s, name, url) => {
	links[name.toLowerCase()] = url;
	return '';
});
```

**Comment by developit** [comment]
Merged and published as 1.2.2 :)
