### ISSUE TITLE
Header doesn't parse reference links propely

### ISSUE THREAD

**Issue by gribnoysup** [developit/snarkdown#16]
Right now reference links in headers are not parsed properly. This markdown

```markdown
# This is a header [with link]

[with link]: http://example.com
```

will generate this html

```html
<h1>This is a header <a href="undefined">with link</a></h1>
```

This happens because `links` object is not in context on the time of links generation. The easiest fix will be to move `links` declaration to the global scope of the module. The other solution could be to somehow pass `links` object to the nested `parse` call, something like that:

```js
export default function parse(md, links = {}) {
// ...
	chunk = '<'+t+'>' + parse(token[12] || token[15], links) + '</'+t+'>';
```

but this will change `parse` function api, so I'm not sure this solution is any good

I'll be happy to submit a PR if any of this solutions are acceptable 😸

**Comment by developit** [comment]
Ah, that's a good point.  I think your section option (passing context to the child parser) is much preferred, though honestly since recursive parsing is synchronous it could probably just go in the global scope.
