### ISSUE TITLE
Update to ES2015 via Rollup + Bublé

### ISSUE THREAD

**Issue by developit** [developit/snarkdown#2]
- [x] Port tooling from [mitt](https://git.io/mitt) or [unfetch](https://git.io/unfetch)
- [x] Switch from custom `trim()` to `String.prototype.trim()`
- [x] Remove likely unnecessary pretty-printing whitespace

**Comment by greggb** [comment]
> Switch from custom trim() to String.prototype.trim()

It looks like the regex  (`(^\n+|\n+$)`) in the custom `trim()` strips newlines not whitespace. It doesn't look the native `string.prototype.trim()` supports that. Were you looking to extend that functionality?

**Comment by developit** [comment]
Fixed in 1.0.0!
