### ISSUE TITLE
Is snarkdown.es.js can be work in browser?

### ISSUE THREAD

**Issue by sufuf3** [developit/snarkdown#39]
Hi @developit ,
We are cdnjs team, we're going to host this library.
Would you mind giving me some suggestion about `snarkdown.es.js`?
I know this file is work fine in Nodejs environment, but not sure this file can be also work fine in browser (web front-end), like `<script src="snarkdown.es.js"></script>`

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11830

**Comment by tbjgolden** [comment]
@sufuf3 yeah there's no need to host that file on cdnjs

**Comment by tbjgolden** [comment]
Following up - there's actually no difference in the content of

`dist/snarkdown.js` and `dist/snarkdown.es.js`

**Comment by sufuf3** [comment]
Got it.
Thank you.
