### ISSUE TITLE
simple editor as preact component

### ISSUE THREAD

**Issue by jojo05** [developit/snarkdown#58]
How would you convert the simple editor example into a preact component ?

 let $ = document.querySelector.bind(document);
 let html = snarkdown($('#in').value);
 $('#out').innerHTML = html;
 $('#code').textContent = html;

**Comment by Kanaye** [comment]
A really simple preact component only using preact, [linkstate](https://github.com/developit/linkstate) and snarkdown could look like [this](https://codesandbox.io/s/rmnyvxk1n4).
If you want be able to use preact components from your markdown you may want to take a look at [preact-markup](https://github.com/developit/preact-markup/).

**Comment by jojo05** [comment]
thanks, exactly what I was looking for
