### ISSUE TITLE
bug: crashes browser tab when * or _ is used

### ISSUE THREAD

**Issue by Hotell** [developit/snarkdown#7]
When using as live editor it crashes/freezes active tab

- try to paste `_` or `*` in textarea within your demo http://jsfiddle.net/developit/828w6t1x/

Havoc will follow :(

**Comment by developit** [comment]
whoop! indeed it does.

**Comment by developit** [comment]
Turns out my clever optimization of [this loop](https://github.com/developit/snarkdown/blob/master/src/index.js#L116) is not so clever

**Comment by Hotell** [comment]
That was quick! Thx! 🍻

**Comment by developit** [comment]
Crashers are my least favorite kind of bug :P

**Comment by Hotell** [comment]
Haha yup. Anyway good job!
