### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by AnandChowdhary** [developit/snarkdown#73]
There's no types for the package available, both within the package or using `@types/snarkdown`. 😢

**Comment by AnandChowdhary** [comment]
I've made a pull request #74 which fixes this!

**Comment by florianmrz** [comment]
When installing from npm (Version 1.2.2), I end up without the type declarations, the package only includes a `src` and a `dist` folder. Are these being omitted when publishing to npm?

See https://unpkg.com/browse/snarkdown@1.2.2/
