### ISSUE TITLE
JS Syntax Highlighting

### ISSUE THREAD

**Issue by mesqueeb** [developit/snarkdown#79]
Hey!
I love this small footprint!!

I'd love to be able to write:
` ```js `
console.log() // etc.
` ``` `
with javascript code and have syntax highlighting for the code block. ;)

I researched a bit and found out I'd need to use Prism
https://prismjs.com

Is it possible to add a small example to the readme to show the best practice of how this could be done? 😄 

Thanks so much!!

**Comment by mesqueeb** [comment]
I did some more research, and PrismJS is very bad at automatic treeshaking...
It says you need an extra "babel-plugin-prismjs" to make the package smaller with just what you need...
<img width="950" alt="image" src="https://user-images.githubusercontent.com/3253920/67135839-35cab900-f259-11e9-8a16-c3408c2375f9.png">

**Comment by tomByrer** [comment]
You could just post-process the resulting HTML?
You need to add a `class="language-js"` to each `<code>` block.
Then read the "Usage with CDNs" section.  I recommend jsDelivr, sin CDNjs future is up in the air.

**Comment by mesqueeb** [comment]
@tomByrer I'm not sure about CDN's I rather package my libraries together with the app via webpack. But if prismjs doesn't support simple tree-shaking, that's such a bummer. :D
because it'll get big you see?

**Comment by mesqueeb** [comment]
@tomByrer how to add ` class="language-js"` to the `<pre>` blocks that snarkdown gives?
