### ISSUE TITLE
module not defined

### ISSUE THREAD

**Issue by kredodevnicolas** [developit/snarkdown#88]
I have included Snarkdown on like this:

![image](https://user-images.githubusercontent.com/64056086/83146868-72cd2700-a129-11ea-8116-a1e55923ccdf.png)

But returns 2 errors:
![image](https://user-images.githubusercontent.com/64056086/83146984-a019d500-a129-11ea-8692-f76c0ccc329d.png)

How do I fix this?

**Comment by developit** [comment]
Hi - please use the UMD bundle:

https://unpkg.com/snarkdown@1.2.2/dist/snarkdown.umd.js
