### ISSUE TITLE
Type declarations missing in npm package

### ISSUE THREAD

**Issue by florianmrz** [developit/snarkdown#89]
When installing from npm (Version 1.2.2), I end up without the type declarations. 
See https://unpkg.com/browse/snarkdown@1.2.2/ for a list of files in the package.

Are these being omitted when publishing to npm? Is the version on npm simply outdated?

**Comment by jonathonherbert** [comment]
I'm also having the same issue.

**Comment by developit** [comment]
Fixed in #86. Sorry about that!
